/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EtudiantRouteImport } from './routes/etudiant'
import { Route as EnseignantRouteImport } from './routes/enseignant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtudiantDashboardRouteImport } from './routes/etudiant.dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantRoute = EtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => rootRouteImport,
} as any)
const EnseignantRoute = EnseignantRouteImport.update({
  id: '/enseignant',
  path: '/enseignant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantDashboardRoute = EtudiantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EtudiantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enseignant': typeof EnseignantRoute
  '/etudiant': typeof EtudiantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enseignant': typeof EnseignantRoute
  '/etudiant': typeof EtudiantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enseignant': typeof EnseignantRoute
  '/etudiant': typeof EtudiantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/enseignant'
    | '/etudiant'
    | '/login'
    | '/register'
    | '/etudiant/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/enseignant'
    | '/etudiant'
    | '/login'
    | '/register'
    | '/etudiant/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/enseignant'
    | '/etudiant'
    | '/login'
    | '/register'
    | '/etudiant/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EnseignantRoute: typeof EnseignantRoute
  EtudiantRoute: typeof EtudiantRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant': {
      id: '/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof EtudiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enseignant': {
      id: '/enseignant'
      path: '/enseignant'
      fullPath: '/enseignant'
      preLoaderRoute: typeof EnseignantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/dashboard': {
      id: '/etudiant/dashboard'
      path: '/dashboard'
      fullPath: '/etudiant/dashboard'
      preLoaderRoute: typeof EtudiantDashboardRouteImport
      parentRoute: typeof EtudiantRoute
    }
  }
}

interface EtudiantRouteChildren {
  EtudiantDashboardRoute: typeof EtudiantDashboardRoute
}

const EtudiantRouteChildren: EtudiantRouteChildren = {
  EtudiantDashboardRoute: EtudiantDashboardRoute,
}

const EtudiantRouteWithChildren = EtudiantRoute._addFileChildren(
  EtudiantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EnseignantRoute: EnseignantRoute,
  EtudiantRoute: EtudiantRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
