/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EtudiantRouteImport } from './routes/etudiant'
import { Route as EnseignantRouteImport } from './routes/enseignant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtudiantSujetsRouteImport } from './routes/etudiant.sujets'
import { Route as EtudiantRapportRouteImport } from './routes/etudiant.rapport'
import { Route as EtudiantProjetRouteImport } from './routes/etudiant.projet'
import { Route as EtudiantEvaluationsRouteImport } from './routes/etudiant.evaluations'
import { Route as EtudiantDashboardRouteImport } from './routes/etudiant.dashboard'
import { Route as EnseignantDashboardRouteImport } from './routes/enseignant.dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantRoute = EtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => rootRouteImport,
} as any)
const EnseignantRoute = EnseignantRouteImport.update({
  id: '/enseignant',
  path: '/enseignant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantSujetsRoute = EtudiantSujetsRouteImport.update({
  id: '/sujets',
  path: '/sujets',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantRapportRoute = EtudiantRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantProjetRoute = EtudiantProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantEvaluationsRoute = EtudiantEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantDashboardRoute = EtudiantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EtudiantRoute,
} as any)
const EnseignantDashboardRoute = EnseignantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EnseignantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enseignant': typeof EnseignantRouteWithChildren
  '/etudiant': typeof EtudiantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/enseignant/dashboard': typeof EnseignantDashboardRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
  '/etudiant/evaluations': typeof EtudiantEvaluationsRoute
  '/etudiant/projet': typeof EtudiantProjetRoute
  '/etudiant/rapport': typeof EtudiantRapportRoute
  '/etudiant/sujets': typeof EtudiantSujetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enseignant': typeof EnseignantRouteWithChildren
  '/etudiant': typeof EtudiantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/enseignant/dashboard': typeof EnseignantDashboardRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
  '/etudiant/evaluations': typeof EtudiantEvaluationsRoute
  '/etudiant/projet': typeof EtudiantProjetRoute
  '/etudiant/rapport': typeof EtudiantRapportRoute
  '/etudiant/sujets': typeof EtudiantSujetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/enseignant': typeof EnseignantRouteWithChildren
  '/etudiant': typeof EtudiantRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/enseignant/dashboard': typeof EnseignantDashboardRoute
  '/etudiant/dashboard': typeof EtudiantDashboardRoute
  '/etudiant/evaluations': typeof EtudiantEvaluationsRoute
  '/etudiant/projet': typeof EtudiantProjetRoute
  '/etudiant/rapport': typeof EtudiantRapportRoute
  '/etudiant/sujets': typeof EtudiantSujetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/enseignant'
    | '/etudiant'
    | '/login'
    | '/register'
    | '/enseignant/dashboard'
    | '/etudiant/dashboard'
    | '/etudiant/evaluations'
    | '/etudiant/projet'
    | '/etudiant/rapport'
    | '/etudiant/sujets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/enseignant'
    | '/etudiant'
    | '/login'
    | '/register'
    | '/enseignant/dashboard'
    | '/etudiant/dashboard'
    | '/etudiant/evaluations'
    | '/etudiant/projet'
    | '/etudiant/rapport'
    | '/etudiant/sujets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/enseignant'
    | '/etudiant'
    | '/login'
    | '/register'
    | '/enseignant/dashboard'
    | '/etudiant/dashboard'
    | '/etudiant/evaluations'
    | '/etudiant/projet'
    | '/etudiant/rapport'
    | '/etudiant/sujets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EnseignantRoute: typeof EnseignantRouteWithChildren
  EtudiantRoute: typeof EtudiantRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant': {
      id: '/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof EtudiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enseignant': {
      id: '/enseignant'
      path: '/enseignant'
      fullPath: '/enseignant'
      preLoaderRoute: typeof EnseignantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/sujets': {
      id: '/etudiant/sujets'
      path: '/sujets'
      fullPath: '/etudiant/sujets'
      preLoaderRoute: typeof EtudiantSujetsRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/rapport': {
      id: '/etudiant/rapport'
      path: '/rapport'
      fullPath: '/etudiant/rapport'
      preLoaderRoute: typeof EtudiantRapportRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/projet': {
      id: '/etudiant/projet'
      path: '/projet'
      fullPath: '/etudiant/projet'
      preLoaderRoute: typeof EtudiantProjetRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/evaluations': {
      id: '/etudiant/evaluations'
      path: '/evaluations'
      fullPath: '/etudiant/evaluations'
      preLoaderRoute: typeof EtudiantEvaluationsRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/dashboard': {
      id: '/etudiant/dashboard'
      path: '/dashboard'
      fullPath: '/etudiant/dashboard'
      preLoaderRoute: typeof EtudiantDashboardRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/enseignant/dashboard': {
      id: '/enseignant/dashboard'
      path: '/dashboard'
      fullPath: '/enseignant/dashboard'
      preLoaderRoute: typeof EnseignantDashboardRouteImport
      parentRoute: typeof EnseignantRoute
    }
  }
}

interface EnseignantRouteChildren {
  EnseignantDashboardRoute: typeof EnseignantDashboardRoute
}

const EnseignantRouteChildren: EnseignantRouteChildren = {
  EnseignantDashboardRoute: EnseignantDashboardRoute,
}

const EnseignantRouteWithChildren = EnseignantRoute._addFileChildren(
  EnseignantRouteChildren,
)

interface EtudiantRouteChildren {
  EtudiantDashboardRoute: typeof EtudiantDashboardRoute
  EtudiantEvaluationsRoute: typeof EtudiantEvaluationsRoute
  EtudiantProjetRoute: typeof EtudiantProjetRoute
  EtudiantRapportRoute: typeof EtudiantRapportRoute
  EtudiantSujetsRoute: typeof EtudiantSujetsRoute
}

const EtudiantRouteChildren: EtudiantRouteChildren = {
  EtudiantDashboardRoute: EtudiantDashboardRoute,
  EtudiantEvaluationsRoute: EtudiantEvaluationsRoute,
  EtudiantProjetRoute: EtudiantProjetRoute,
  EtudiantRapportRoute: EtudiantRapportRoute,
  EtudiantSujetsRoute: EtudiantSujetsRoute,
}

const EtudiantRouteWithChildren = EtudiantRoute._addFileChildren(
  EtudiantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EnseignantRoute: EnseignantRouteWithChildren,
  EtudiantRoute: EtudiantRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
